include(`configs/snmp')dnl
include(`configs/vlan')dnl
include(`configs/ipif')dnl
include(`configs/standart')dnl
include(`configs/radius')dnl
include(`configs/auth')dnl
include(`configs/auth.localen')dnl
include(`configs/stp')dnl
include(`configs/addressbinding')dnl
include(`configs/acl')dnl
include(`configs/save')dnl
